// rsadispa.h
// Dispatch indices for RSA ObjectWindows interface
// By Tom Weatherhead			September 19, 1994

#define ID_PUBFILE		101
#define ID_PRIVFILE		102
#define ID_KEYSIZE		103
#define ID_BROWSEPUB		104
#define ID_BROWSEPRIV		105
#define ID_BROWSESRC		106
#define ID_BROWSEDEST		107
#define ID_SRCFILE		108
#define ID_DESTFILE		109
#define ID_KEYFILE		110
#define ID_BROWSEKEYS		111
#define ID_LINESPERFILE		112
#define ID_PROGRESSMSG		113

#define CM_FILEEXIT		201
#define CM_RSAGENERATEKEYS	202
#define CM_RSAENCRYPT		203
#define CM_RSADECRYPT		204
#define CM_UUENCODE             205
#define CM_UUDECODE		206
#define CM_HELPABOUT		207


// **** End of rsadispa.h ****
